# Generated by Django 4.0.3 on 2022-03-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_approved_pizza_thumbnail_url_pizzeria_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('meat', 'meat'), ('vegan', 'vegan')], default=('meat', 'meat'), max_length=10),
        ),
    ]
